package io.mikelane.demo.student;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

@Repository
public interface StudentRepository extends JpaRepository<Student, Long> {

  // Could also specify the query with an annotation thusly:
  // @Query("SELECT s from Student s WHERE s.email = ?1")
  Optional<Student> findStudentByEmail(String email);
  // If not specified, the query will be autogenerated.
}
